final products = [
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'price': 14.0,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Addidas Shoes',
    'price': 12.0,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Addidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '2',
    'title': 'Bata Women\'s Shoes',
    'price': 18.0,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': '3',
    'title': 'Puma Shoes',
    'price': 14.5,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Puma',
    'sizes': [8, 9, 10],
  },
  {
    'id': '4',
    'title': 'Nike Shoes',
    'price': 15.5,
    'imageUrl': 'assets/images/shoes_5.jpeg',
    'company': 'Nike',
    'sizes': [9, 10],
  },
  {
    'id': '5',
    'title': 'Puma Shoes',
    'price': 16.5,
    'imageUrl': 'assets/images/shoes_6.jpg',
    'company': 'Puma',
    'sizes': [8, 9],
  },

];
