// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJZ1oucejcbT4huymbXYcZv6uLZ7l4JUA',
    appId: '1:757815644679:web:d021a21037d24700e2d0a2',
    messagingSenderId: '757815644679',
    projectId: 'flutter-firebase-29ae0',
    authDomain: 'flutter-firebase-29ae0.firebaseapp.com',
    storageBucket: 'flutter-firebase-29ae0.appspot.com',
    measurementId: 'G-XLCCZ6T36E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB25ldhi8jT_5Q68SaKIG3Q_SZhb1i-Rhs',
    appId: '1:757815644679:android:33f51c3d43c94541e2d0a2',
    messagingSenderId: '757815644679',
    projectId: 'flutter-firebase-29ae0',
    storageBucket: 'flutter-firebase-29ae0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChZdK7SxW9mEIh5kTwXJ1jvZIqzDWqjfg',
    appId: '1:757815644679:ios:5455a5cd52301367e2d0a2',
    messagingSenderId: '757815644679',
    projectId: 'flutter-firebase-29ae0',
    storageBucket: 'flutter-firebase-29ae0.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChZdK7SxW9mEIh5kTwXJ1jvZIqzDWqjfg',
    appId: '1:757815644679:ios:1ad484b62921978de2d0a2',
    messagingSenderId: '757815644679',
    projectId: 'flutter-firebase-29ae0',
    storageBucket: 'flutter-firebase-29ae0.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
